/*
 * Auto-generated C API header for web-phone wpffi crate.
 * Generated by cbindgen. Do not edit manually.
 */

#ifndef WPFFI_H
#define WPFFI_H

/* Warning, this file is autogenerated by cbindgen. Don't edit this file manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque handle representing an active audio call session.
 */
typedef struct WPFFICallHandle WPFFICallHandle;

/**
 * Opaque configuration handle for wpclient.
 */
typedef struct WPFFIConfig WPFFIConfig;

/**
 * Retrieve the last thread-local error message string if any C API call returned non-zero error status.
 * The returned pointer is managed internally and must NOT be freed by the caller.
 */
const char *wpffi_last_error_message(void);

/**
 * Initialize tracing subscriber for logging output.
 * Returns 0 on success, or -1 on error.
 */
int wpffi_init(void);

/**
 * Create a new client configuration handle with default settings.
 */
struct WPFFIConfig *wpffi_config_new(void);

/**
 * Free a configuration handle created with `wpffi_config_new`.
 * # Safety
 * `config` must be a valid pointer created by `wpffi_config_new`, or NULL.
 */
void wpffi_config_free(struct WPFFIConfig *config);

/**
 * Set server IP address (IPv4 or IPv6 string) and port.
 * Returns 0 on success, or -1 on error.
 * # Safety
 * `config` and `server_ip` must be valid non-null pointers.
 */
int wpffi_config_set_server(struct WPFFIConfig *config,
                            const char *server_ip,
                            uint16_t server_port);

/**
 * Set STUN server URL (e.g., "stun:127.0.0.1:3478").
 * Returns 0 on success, or -1 on error.
 * # Safety
 * `config` and `stun_server` must be valid non-null pointers.
 */
int wpffi_config_set_stun_server(struct WPFFIConfig *config, const char *stun_server);

/**
 * Set auto-accept flag for incoming call requests without CLI prompts.
 * Returns 0 on success, or -1 on error.
 * # Safety
 * `config` must be a valid non-null pointer.
 */
int wpffi_config_set_auto_accept(struct WPFFIConfig *config, bool auto_accept);

/**
 * Set allow-echoback flag (hear own voice).
 * Returns 0 on success, or -1 on error.
 * # Safety
 * `config` must be a valid non-null pointer.
 */
int wpffi_config_set_allow_echoback(struct WPFFIConfig *config, bool allow_echoback);

/**
 * Set input/output audio device substring overrides (pass NULL to leave unchanged or use default).
 * Returns 0 on success, or -1 on error.
 * # Safety
 * `config` must be a valid non-null pointer. `input_device` and `output_device` must be valid C strings or NULL.
 */
int wpffi_config_set_audio_devices(struct WPFFIConfig *config,
                                   const char *input_device,
                                   const char *output_device);

/**
 * Query registered user addresses from wpdaemon server as a JSON string array.
 * Caller must free `*out_json` using `wpffi_string_free`.
 * Returns 0 on success, or -1 on error.
 * # Safety
 * `config` and `out_json` must be valid non-null pointers.
 */
int wpffi_list_addresses(const struct WPFFIConfig *config, char **out_json);

/**
 * Query available audio input and output devices as a JSON object.
 * Caller must free `*out_json` using `wpffi_string_free`.
 * Returns 0 on success, or -1 on error.
 * # Safety
 * `out_json` must be a valid non-null pointer.
 */
int wpffi_list_audio_devices(char **out_json);

/**
 * Start an audio call session in a background worker thread.
 * `target_address` can be NULL to operate in standby mode, or a valid UserAddress SHA-256 string.
 * Returns pointer to `WPFFICallHandle` on success, or NULL on error.
 * # Safety
 * `config` must be a valid non-null pointer. `target_address` must be a valid C string or NULL.
 */
struct WPFFICallHandle *wpffi_call_start(const struct WPFFIConfig *config,
                                         const char *target_address);

/**
 * Stop and terminate an active call session, freeing its handle.
 * Returns 0 on success, or -1 on error.
 * # Safety
 * `handle` must be a valid pointer returned by `wpffi_call_start`.
 */
int wpffi_call_stop(struct WPFFICallHandle *handle);

/**
 * Free a C string allocated by `wpffi_list_addresses` or `wpffi_list_audio_devices`.
 * # Safety
 * `ptr` must be a pointer allocated by `wpffi_list_addresses` or `wpffi_list_audio_devices`, or NULL.
 */
void wpffi_string_free(char *ptr);

#endif  /* WPFFI_H */
