[package]
name = "wpclient"
version.workspace = true
description = "WebRTC client CLI for real-time audio transmission"
edition.workspace = true

[dependencies]
wpapi = { path = "../wpapi" }
anyhow.workspace = true
clap.workspace = true
color-eyre.workspace = true
confy.workspace = true
reqwest.workspace = true

tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
ratatui.workspace = true
crossterm.workspace = true
futures.workspace = true
cpal.workspace = true


[dev-dependencies]
toml.workspace = true
