//! Address / User ID module for identifying wpclient users.
//!
//! This module provides the `UserAddress` struct representing a temporary user ID
//! generated by `wpdaemon` using a SHA-256 hash of the UNIX timestamp.

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::fmt;
use std::str::FromStr;
use std::sync::atomic::{AtomicU64, Ordering};
use std::time::{SystemTime, UNIX_EPOCH};

/// Global counter for tie-breaking SHA-256 generation in the same nanosecond.
static TIME_COUNTER: AtomicU64 = AtomicU64::new(0);

/// Temporary user address / ID generated from UNIX timestamp SHA-256 hash.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct UserAddress {
    /// SHA-256 hash string (hexadecimal representation).
    pub id: String,
}

impl UserAddress {
    /// Create a `UserAddress` from a hex ID string.
    pub fn new(id: impl Into<String>) -> Self {
        Self { id: id.into() }
    }

    /// Generate a temporary `UserAddress` using SHA-256 hash derived from current UNIX timestamp.
    pub fn generate_from_time() -> Self {
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_nanos();
        let count = TIME_COUNTER.fetch_add(1, Ordering::Relaxed);

        let mut hasher = Sha256::new();
        hasher.update(format!("{}-{}", nanos, count).as_bytes());
        let result = hasher.finalize();
        let hex_id = format!("{:x}", result);

        Self { id: hex_id }
    }

    /// Convert 32-byte SHA-256 raw bytes to `UserAddress`.
    pub fn from_bytes(bytes: [u8; 32]) -> Self {
        Self {
            id: hex_encode(&bytes),
        }
    }

    /// Convert `UserAddress` to 32-byte raw array representation.
    pub fn to_bytes(&self) -> [u8; 32] {
        let mut bytes = [0u8; 32];
        if hex_decode_into(&self.id, &mut bytes) {
            bytes
        } else {
            [0u8; 32]
        }
    }

    /// Return a short 12-character preview string of the SHA-256 ID.
    pub fn short_id(&self) -> &str {
        if self.id.len() >= 12 {
            &self.id[..12]
        } else {
            &self.id
        }
    }

    /// Check if this UserAddress matches another UserAddress by exact or prefix match (handling zero-padded Short IDs).
    pub fn matches_prefix(&self, other: &UserAddress) -> bool {
        if self.id == other.id {
            return true;
        }
        let self_clean = self.id.trim_end_matches('0');
        let other_clean = other.id.trim_end_matches('0');

        (!other_clean.is_empty()
            && other_clean.len() <= self.id.len()
            && self.id.starts_with(other_clean))
            || (!self_clean.is_empty()
                && self_clean.len() <= other.id.len()
                && other.id.starts_with(self_clean))
    }
}

/// Helper function to convert a byte slice into a lower-hex String.
fn hex_encode(bytes: &[u8]) -> String {
    let mut s = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        use std::fmt::Write;
        let _ = write!(s, "{:02x}", b);
    }
    s
}

/// Helper function to decode hex string into a fixed-size byte slice.
fn hex_decode_into(hex_str: &str, out: &mut [u8]) -> bool {
    let bytes = hex_str.as_bytes();
    for (i, byte) in out.iter_mut().enumerate() {
        if i * 2 + 1 < bytes.len()
            && let Ok(val) = u8::from_str_radix(&hex_str[i * 2..i * 2 + 2], 16)
        {
            *byte = val;
        } else {
            return false;
        }
    }
    true
}

/// Self-Sovereign Ed25519 Cryptographic Identity Keypair for wpclient / wpdaemon (WPIP-01, WPIP-02, WPIP-03).
#[derive(Debug)]
pub struct UserKeypair {
    signing_key: ed25519_dalek::SigningKey,
}

impl UserKeypair {
    /// Generate a new random Ed25519 keypair.
    pub fn generate() -> Self {
        let mut rng = rand::rngs::OsRng;
        let signing_key = ed25519_dalek::SigningKey::generate(&mut rng);
        Self { signing_key }
    }

    /// Construct `UserKeypair` from raw 32-byte secret key.
    pub fn from_bytes(bytes: &[u8; 32]) -> Self {
        let signing_key = ed25519_dalek::SigningKey::from_bytes(bytes);
        Self { signing_key }
    }

    /// Return raw 32-byte secret key.
    pub fn to_bytes(&self) -> [u8; 32] {
        self.signing_key.to_bytes()
    }

    /// Get `UserAddress` representing this keypair's 32-byte Ed25519 Public Key (64 hex string).
    pub fn public_key_address(&self) -> UserAddress {
        let verifying_key = self.signing_key.verifying_key();
        UserAddress::from_bytes(verifying_key.to_bytes())
    }

    /// Sign arbitrary byte message using Ed25519 secret key, returning 64-byte hex signature string.
    pub fn sign(&self, message: &[u8]) -> String {
        use ed25519_dalek::Signer;
        let sig = self.signing_key.sign(message);
        hex_encode(&sig.to_bytes())
    }

    /// Cryptographically verify an Ed25519 signature hex string for a given `UserAddress` public key.
    pub fn verify(pubkey_address: &UserAddress, message: &[u8], signature_hex: &str) -> bool {
        use ed25519_dalek::Verifier;
        let pubkey_bytes = pubkey_address.to_bytes();
        let Ok(verifying_key) = ed25519_dalek::VerifyingKey::from_bytes(&pubkey_bytes) else {
            return false;
        };

        if signature_hex.len() != 128 {
            return false;
        }

        let mut sig_bytes = [0u8; 64];
        if !hex_decode_into(signature_hex, &mut sig_bytes) {
            return false;
        }

        let sig = ed25519_dalek::Signature::from_bytes(&sig_bytes);
        verifying_key.verify(message, &sig).is_ok()
    }
}

/// Build HTTP `Authorization` header value per WPIP-02 / WPIP-03: `WP-Ed25519 <PubKeyHex>:<Timestamp>:<SignatureHex>`
pub fn build_authorization_header(keypair: &UserKeypair, sdp_offer: &str) -> (u64, String) {
    let timestamp = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();
    let payload = format!("{}:{}", timestamp, sdp_offer);
    let sig_hex = keypair.sign(payload.as_bytes());
    let header = format!(
        "WP-Ed25519 {}:{}:{}",
        keypair.public_key_address().id,
        timestamp,
        sig_hex
    );
    (timestamp, header)
}

/// Verify HTTP `Authorization` header value per WPIP-02 Section 2.2.
pub fn verify_authorization_header(
    header_val: &str,
    sdp_offer: &str,
) -> Result<UserAddress, String> {
    let val = header_val
        .strip_prefix("WP-Ed25519 ")
        .ok_or("Invalid authorization scheme")?;
    let parts: Vec<&str> = val.split(':').collect();
    if parts.len() != 3 {
        return Err("Invalid authorization header format (expected PubKey:Timestamp:Sig)".into());
    }
    let pubkey_hex = parts[0];
    let timestamp: u64 = parts[1]
        .parse()
        .map_err(|_| "Invalid timestamp in authorization header")?;
    let sig_hex = parts[2];

    let now = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();
    let diff = now.abs_diff(timestamp);
    if diff > 300 {
        return Err(format!(
            "Authorization timestamp drift too large ({}s > 300s)",
            diff
        ));
    }

    let addr = UserAddress::new(pubkey_hex);
    let payload = format!("{}:{}", timestamp, sdp_offer);
    if UserKeypair::verify(&addr, payload.as_bytes(), sig_hex) {
        Ok(addr)
    } else {
        Err("Invalid Ed25519 cryptographic signature".into())
    }
}

impl Default for UserAddress {
    fn default() -> Self {
        Self::generate_from_time()
    }
}

impl fmt::Display for UserAddress {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.id)
    }
}

impl FromStr for UserAddress {
    type Err = std::convert::Infallible;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        Ok(Self {
            id: s.trim().to_string(),
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_ed25519_keypair_sign_verify() {
        let keypair = UserKeypair::generate();
        let pubkey_addr = keypair.public_key_address();
        assert_eq!(pubkey_addr.id.len(), 64);

        let msg = b"1757275200:v=0\r\nt=0 0\r\n";
        let sig_hex = keypair.sign(msg);
        assert_eq!(sig_hex.len(), 128);

        assert!(UserKeypair::verify(&pubkey_addr, msg, &sig_hex));
        assert!(!UserKeypair::verify(&pubkey_addr, b"wrong_msg", &sig_hex));
    }

    #[test]
    fn test_authorization_header_roundtrip() {
        let keypair = UserKeypair::generate();
        let sdp = "v=0\r\no=- 123 456 IN IP4 127.0.0.1\r\n";
        let (_, header) = build_authorization_header(&keypair, sdp);
        let verified_addr = verify_authorization_header(&header, sdp).expect("Verification failed");
        assert_eq!(verified_addr, keypair.public_key_address());
    }

    #[test]
    fn test_user_address_generation_from_time() {
        let addr1 = UserAddress::generate_from_time();
        let addr2 = UserAddress::generate_from_time();

        assert_eq!(addr1.id.len(), 64);
        assert_eq!(addr2.id.len(), 64);
        assert_ne!(addr1, addr2);
    }

    #[test]
    fn test_user_address_bytes_roundtrip() {
        let addr = UserAddress::generate_from_time();
        let bytes = addr.to_bytes();
        let reconstructed = UserAddress::from_bytes(bytes);

        assert_eq!(addr, reconstructed);
    }

    #[test]
    fn test_user_address_short_id() {
        let addr = UserAddress::new("a1b2c3d4e5f607080900");
        assert_eq!(addr.short_id(), "a1b2c3d4e5f6");
    }

    #[test]
    fn test_user_address_serde() {
        let addr = UserAddress::generate_from_time();
        let json_str = serde_json::to_string(&addr).expect("Failed to serialize");
        let deserialized: UserAddress =
            serde_json::from_str(&json_str).expect("Failed to deserialize");

        assert_eq!(addr, deserialized);
    }

    #[test]
    fn test_user_address_short_id_short_length() {
        let addr = UserAddress::new("short");
        assert_eq!(addr.short_id(), "short");
    }

    #[test]
    fn test_user_address_from_str_and_display() {
        let addr_str = "1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef";
        let parsed: UserAddress = addr_str.parse().unwrap();
        assert_eq!(parsed.to_string(), addr_str);
        assert_eq!(parsed.id, addr_str);
    }
}
