//! Address / User ID module for identifying wpclient users.
//!
//! This module provides the `UserAddress` struct representing a temporary user ID
//! generated by `wpdaemon` using a SHA-256 hash of the UNIX timestamp.

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::collections::HashMap;
use std::fmt;
use std::str::FromStr;
use std::sync::Arc;
use std::sync::LazyLock;
use std::sync::RwLock;
use std::sync::atomic::{AtomicU64, Ordering};
use std::time::{SystemTime, UNIX_EPOCH};

/// Global counter for tie-breaking SHA-256 generation in the same nanosecond.
static TIME_COUNTER: AtomicU64 = AtomicU64::new(0);

/// Temporary user address / ID generated from UNIX timestamp SHA-256 hash.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct UserAddress {
    /// SHA-256 hash string (hexadecimal representation).
    pub id: String,
}

impl UserAddress {
    /// Create a `UserAddress` from a hex ID string.
    pub fn new(id: impl Into<String>) -> Self {
        Self { id: id.into() }
    }

    /// Generate a temporary `UserAddress` using SHA-256 hash derived from current UNIX timestamp.
    pub fn generate_from_time() -> Self {
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_nanos();
        let count = TIME_COUNTER.fetch_add(1, Ordering::Relaxed);

        let mut hasher = Sha256::new();
        hasher.update(format!("{}-{}", nanos, count).as_bytes());
        let result = hasher.finalize();
        let hex_id = hex::encode(result);

        Self { id: hex_id }
    }

    /// Convert 32-byte SHA-256 raw bytes to `UserAddress`.
    pub fn from_bytes(bytes: [u8; 32]) -> Self {
        Self {
            id: hex_encode(&bytes),
        }
    }

    /// Convert `UserAddress` to 32-byte raw array representation.
    pub fn to_bytes(&self) -> [u8; 32] {
        let mut raw_buf = [0u8; 32];
        if hex_decode_into(&self.id, &mut raw_buf) {
            raw_buf
        } else {
            [0u8; 32]
        }
    }

    /// Return a short 12-character preview string of the SHA-256 ID.
    pub fn short_id(&self) -> &str {
        if self.id.len() >= 12 {
            &self.id[..12]
        } else {
            &self.id
        }
    }

    /// Check if this UserAddress matches another UserAddress by exact or prefix match (handling zero-padded Short IDs).
    pub fn matches_prefix(&self, other: &UserAddress) -> bool {
        if self.id == other.id {
            return true;
        }
        let self_clean = self.id.trim_end_matches('0');
        let other_clean = other.id.trim_end_matches('0');

        (!other_clean.is_empty()
            && other_clean.len() <= self.id.len()
            && self.id.starts_with(other_clean))
            || (!self_clean.is_empty()
                && self_clean.len() <= other.id.len()
                && other.id.starts_with(self_clean))
    }
}

/// Helper function to convert a byte slice into a lower-hex String.
fn hex_encode(bytes: &[u8]) -> String {
    let mut s = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        use std::fmt::Write;
        let _ = write!(s, "{:02x}", b);
    }
    s
}

/// Helper function to decode hex string into a fixed-size byte slice.
fn hex_decode_into(hex_str: &str, out: &mut [u8]) -> bool {
    let bytes = hex_str.as_bytes();
    out.fill(0);
    let hex_len = bytes.len() - (bytes.len() % 2);
    if hex_len == 0 {
        return false;
    }
    for i in 0..(hex_len / 2).min(out.len()) {
        if let Ok(val) = u8::from_str_radix(&hex_str[i * 2..i * 2 + 2], 16) {
            out[i] = val;
        } else {
            return false;
        }
    }
    true
}

const BECH32_CHARSET: &[u8; 32] = b"qpzry9x8gf2tvdw0s3jn54khce6mua7l";

fn bech32_polymod(values: &[u32]) -> u32 {
    let mut chk: u32 = 1;
    for &v in values {
        let top = chk >> 25;
        chk = ((chk & 0x1ffffff) << 5) ^ v;
        if (top & 1) != 0 {
            chk ^= 0x3b6a57b2;
        }
        if (top & 2) != 0 {
            chk ^= 0x26508e6d;
        }
        if (top & 4) != 0 {
            chk ^= 0x1ea119fa;
        }
        if (top & 8) != 0 {
            chk ^= 0x3d4233dd;
        }
        if (top & 16) != 0 {
            chk ^= 0x2a1462b3;
        }
    }
    chk
}

fn hrp_expand(hrp: &str) -> Vec<u32> {
    let mut v = Vec::new();
    for b in hrp.bytes() {
        v.push((b >> 5) as u32);
    }
    v.push(0);
    for b in hrp.bytes() {
        v.push((b & 31) as u32);
    }
    v
}

fn verify_bech32_checksum(hrp: &str, data: &[u32]) -> bool {
    let mut exp = hrp_expand(hrp);
    exp.extend_from_slice(data);
    bech32_polymod(&exp) == 1
}

/// Decode Bech32 encoded string into HRP and 5-bit payload data.
pub fn decode_bech32(s: &str) -> Result<(String, Vec<u32>), String> {
    let s_lower = s.to_lowercase();
    let pos = s_lower.rfind('1').ok_or("Missing Bech32 separator '1'")?;
    if pos == 0 || pos + 7 > s_lower.len() {
        return Err("Invalid Bech32 string length".to_string());
    }
    let hrp = &s_lower[..pos];
    let data_part = &s_lower[pos + 1..];
    let mut data = Vec::with_capacity(data_part.len());
    for c in data_part.chars() {
        let idx = BECH32_CHARSET
            .iter()
            .position(|&b| b as char == c)
            .ok_or_else(|| format!("Invalid Bech32 character: {}", c))?;
        data.push(idx as u32);
    }

    if !verify_bech32_checksum(hrp, &data) {
        return Err("Invalid Bech32 checksum".to_string());
    }

    if data.len() < 6 {
        return Err("Bech32 payload too short".to_string());
    }
    let payload = data[..data.len() - 6].to_vec();
    Ok((hrp.to_string(), payload))
}

/// Convert 5-bit array to 8-bit array or vice versa.
pub fn convert_bits(
    data: &[u32],
    from_bits: u32,
    to_bits: u32,
    pad: bool,
) -> Result<Vec<u8>, String> {
    let mut acc: u32 = 0;
    let mut bits: u32 = 0;
    let mut ret = Vec::new();
    let maxv: u32 = (1 << to_bits) - 1;
    let max_acc: u32 = (1 << (from_bits + to_bits - 1)) - 1;

    for &value in data {
        if value >> from_bits != 0 {
            return Err("Invalid bit value".to_string());
        }
        acc = ((acc << from_bits) | value) & max_acc;
        bits += from_bits;
        while bits >= to_bits {
            bits -= to_bits;
            ret.push(((acc >> bits) & maxv) as u8);
        }
    }

    if pad {
        if bits > 0 {
            ret.push(((acc << (to_bits - bits)) & maxv) as u8);
        }
    } else if bits >= from_bits || ((acc << (to_bits - bits)) & maxv) != 0 {
        return Err("Invalid padding in Bech32 bit conversion".to_string());
    }

    Ok(ret)
}

fn create_bech32_checksum(hrp: &str, data: &[u32]) -> Vec<u32> {
    let mut values = hrp_expand(hrp);
    values.extend_from_slice(data);
    values.extend_from_slice(&[0, 0, 0, 0, 0, 0]);
    let polymod = bech32_polymod(&values) ^ 1;
    let mut ret = Vec::with_capacity(6);
    for i in 0..6 {
        ret.push((polymod >> (5 * (5 - i))) & 31);
    }
    ret
}

/// Encode 8-bit byte slice to Bech32 string with specified HRP prefix.
pub fn encode_bech32(hrp: &str, data_8bit: &[u8]) -> Result<String, String> {
    let u32_data: Vec<u32> = data_8bit.iter().map(|&b| b as u32).collect();
    let data_5bit = convert_bits(&u32_data, 8, 5, true)?;
    let data_5bit_u32: Vec<u32> = data_5bit.iter().map(|&b| b as u32).collect();
    let checksum = create_bech32_checksum(hrp, &data_5bit_u32);
    let mut combined = data_5bit_u32;
    combined.extend_from_slice(&checksum);

    let mut result = String::new();
    result.push_str(hrp);
    result.push('1');
    for v in combined {
        result.push(BECH32_CHARSET[v as usize] as char);
    }
    Ok(result)
}

/// Parse a Nostr key (`nsec1...`, `npub1...`, or 64-character Hex string) into 32 raw bytes.
pub fn parse_nostr_key_to_bytes(input: &str) -> Result<[u8; 32], String> {
    let trimmed = input.trim();
    if trimmed.len() == 64 {
        let bytes = hex::decode(trimmed).map_err(|e| format!("Invalid hex: {}", e))?;
        let arr = <[u8; 32]>::try_from(bytes.as_slice())
            .map_err(|_| "Invalid hex byte length".to_string())?;
        return Ok(arr);
    }

    if trimmed.starts_with("nsec1") || trimmed.starts_with("npub1") {
        let (hrp, data_5bit) = decode_bech32(trimmed)?;
        if hrp != "nsec" && hrp != "npub" {
            return Err(format!("Unsupported Bech32 HRP prefix: {}", hrp));
        }
        let data_8bit = convert_bits(&data_5bit, 5, 8, false)?;
        let arr = <[u8; 32]>::try_from(data_8bit.as_slice()).map_err(|_| {
            format!(
                "Invalid Bech32 payload length: expected 32 bytes, got {}",
                data_8bit.len()
            )
        })?;
        return Ok(arr);
    }

    Err("Invalid Nostr key format (expected 64-char Hex or nsec1.../npub1... Bech32)".to_string())
}

#[derive(Clone)]
enum KeypairKind {
    Ed25519(ed25519_dalek::SigningKey),
    Secp256k1(k256::schnorr::SigningKey),
}

impl fmt::Debug for KeypairKind {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            KeypairKind::Ed25519(_) => write!(f, "KeypairKind::Ed25519(...)"),
            KeypairKind::Secp256k1(_) => write!(f, "KeypairKind::Secp256k1(...)"),
        }
    }
}

/// Cryptographic Identity Keypair for wpclient / wpdaemon supporting Ed25519 (WPIP-01..03) and Secp256k1 / Nostr (WPIP-16).
#[derive(Debug, Clone)]
pub struct UserKeypair {
    kind: KeypairKind,
}

impl UserKeypair {
    /// Generate a new random Ed25519 keypair.
    pub fn generate() -> Self {
        let mut rng = rand::rngs::OsRng;
        let signing_key = ed25519_dalek::SigningKey::generate(&mut rng);
        Self {
            kind: KeypairKind::Ed25519(signing_key),
        }
    }

    /// Construct Ed25519 `UserKeypair` from raw 32-byte secret key.
    pub fn from_bytes(bytes: &[u8; 32]) -> Self {
        let signing_key = ed25519_dalek::SigningKey::from_bytes(bytes);
        Self {
            kind: KeypairKind::Ed25519(signing_key),
        }
    }

    /// Construct Secp256k1 / Nostr `UserKeypair` from raw 32-byte secret key.
    pub fn from_secp256k1_bytes(bytes: &[u8; 32]) -> Result<Self, String> {
        let signing_key = k256::schnorr::SigningKey::from_bytes(bytes)
            .map_err(|e| format!("Invalid secp256k1 secret key: {}", e))?;
        Ok(Self {
            kind: KeypairKind::Secp256k1(signing_key),
        })
    }

    /// Construct Secp256k1 / Nostr `UserKeypair` from `nsec1...` Bech32 or 64-char Hex string.
    pub fn from_nostr_key(key_str: &str) -> Result<Self, String> {
        let bytes = parse_nostr_key_to_bytes(key_str)?;
        Self::from_secp256k1_bytes(&bytes)
    }

    /// Return raw 32-byte secret key.
    pub fn to_bytes(&self) -> [u8; 32] {
        match &self.kind {
            KeypairKind::Ed25519(sk) => sk.to_bytes(),
            KeypairKind::Secp256k1(sk) => {
                let bytes: [u8; 32] = sk.to_bytes().into();
                bytes
            }
        }
    }

    /// Get `UserAddress` representing this keypair's public key (64 hex string).
    pub fn public_key_address(&self) -> UserAddress {
        match &self.kind {
            KeypairKind::Ed25519(sk) => {
                let verifying_key = sk.verifying_key();
                UserAddress::from_bytes(verifying_key.to_bytes())
            }
            KeypairKind::Secp256k1(sk) => {
                let verifying_key = sk.verifying_key();
                let bytes = verifying_key.to_bytes();
                UserAddress::new(hex::encode(bytes))
            }
        }
    }

    /// Sign arbitrary byte message using secret key, returning hex signature string.
    pub fn sign(&self, message: &[u8]) -> String {
        match &self.kind {
            KeypairKind::Ed25519(sk) => {
                use ed25519_dalek::Signer;
                let sig = sk.sign(message);
                hex_encode(&sig.to_bytes())
            }
            KeypairKind::Secp256k1(sk) => {
                use k256::schnorr::signature::Signer;
                let sig: k256::schnorr::Signature = sk.sign(message);
                hex::encode(sig.to_bytes())
            }
        }
    }

    /// Check if keypair is Secp256k1 / Nostr key.
    pub fn is_secp256k1(&self) -> bool {
        matches!(self.kind, KeypairKind::Secp256k1(_))
    }

    /// Cryptographically verify an Ed25519 or Secp256k1 signature hex string for a given `UserAddress` public key.
    pub fn verify(pubkey_address: &UserAddress, message: &[u8], signature_hex: &str) -> bool {
        use ed25519_dalek::Verifier;
        let pubkey_bytes = pubkey_address.to_bytes();
        if signature_hex.len() == 128 {
            let Ok(verifying_key) = ed25519_dalek::VerifyingKey::from_bytes(&pubkey_bytes) else {
                return false;
            };
            let mut sig_buf = [0u8; 64];
            if hex_decode_into(signature_hex, &mut sig_buf)
                && verifying_key
                    .verify(message, &ed25519_dalek::Signature::from_bytes(&sig_buf))
                    .is_ok()
            {
                return true;
            }
        }

        if let Ok(pubkey_bytes) = hex::decode(&pubkey_address.id) {
            let Ok(verifying_key) = k256::schnorr::VerifyingKey::from_bytes(&pubkey_bytes) else {
                return false;
            };
            let Ok(sig_bytes) = hex::decode(signature_hex) else {
                return false;
            };
            let Ok(sig) = k256::schnorr::Signature::try_from(sig_bytes.as_slice()) else {
                return false;
            };
            use k256::schnorr::signature::Verifier;
            if verifying_key.verify(message, &sig).is_ok() {
                return true;
            }
        }

        false
    }
}

/// Build HTTP `Authorization` header value per WPIP-02 / WPIP-03 (`WP-Ed25519`) or WPIP-16 (`WP-Secp256k1`).
pub fn build_authorization_header(keypair: &UserKeypair, sdp_offer: &str) -> (u64, String) {
    let timestamp = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();
    let payload = format!("{}:{}", timestamp, sdp_offer);
    let sig_hex = keypair.sign(payload.as_bytes());
    let scheme = if keypair.is_secp256k1() {
        "WP-Secp256k1"
    } else {
        "WP-Ed25519"
    };
    let header = format!(
        "{} {}:{}:{}",
        scheme,
        keypair.public_key_address().id,
        timestamp,
        sig_hex
    );
    (timestamp, header)
}

/// Maximum allowable time drift (±300 seconds) for Authorization header timestamps (WPIP-02 / WPIP-16).
pub const MAX_TIMESTAMP_DRIFT_SECS: u64 = 300;

use thiserror::Error;

/// Authentication and authorization errors per WPIP-02 / WPIP-10 / WPIP-16.
#[derive(Debug, Error, PartialEq, Eq, Clone)]
pub enum AuthError {
    #[error("Invalid authorization scheme: {0}")]
    InvalidScheme(String),

    #[error("Invalid authorization header format (expected PubKey:Timestamp:Sig)")]
    InvalidHeaderFormat,

    #[error("Invalid timestamp in authorization header")]
    InvalidTimestamp,

    #[error("Authorization timestamp drift too large ({diff}s > {max}s)")]
    TimestampDrift { diff: u64, max: u64 },

    #[error("Invalid Ed25519 cryptographic signature")]
    InvalidEd25519Signature,

    #[error("Invalid secp256k1 public key format")]
    InvalidSecp256k1Key,

    #[error("Invalid secp256k1 Schnorr cryptographic signature")]
    InvalidSecp256k1Signature,

    #[error("Invalid hex encoding: {0}")]
    InvalidHex(String),

    #[error("Replay attack detected: signature already used")]
    ReplayDetected,

    #[error("Invalid TURN username format (expected timestamp:user_address_hex)")]
    InvalidTurnUsernameFormat,

    #[error("TURN credential expired (expired at {expired_at}, current time {current_time})")]
    TurnCredentialExpired { expired_at: u64, current_time: u64 },

    #[error("Invalid TURN credential signature")]
    InvalidTurnSignature,

    #[error("Invalid Base64 encoding in TURN credential")]
    InvalidTurnBase64,
}

/// Anti-replay signature cache to prevent handshake replay attacks within the valid timestamp window.
#[derive(Debug, Clone, Default)]
pub struct AntiReplayCache {
    signatures: Arc<RwLock<HashMap<String, u64>>>,
}

impl AntiReplayCache {
    pub fn new() -> Self {
        Self {
            signatures: Arc::new(RwLock::new(HashMap::new())),
        }
    }

    /// Check if a signature has already been used within the acceptable time window.
    /// If signature is unique, records it and returns `Ok(())`.
    /// Otherwise returns `Err(AuthError::ReplayDetected)`.
    pub fn check_and_insert(
        &self,
        signature: &str,
        timestamp: u64,
        now: u64,
    ) -> Result<(), AuthError> {
        let mut map = self.signatures.write().unwrap();

        // Retain entries within 300s window relative to current time `now`
        map.retain(|_, &mut ts| now.abs_diff(ts) <= MAX_TIMESTAMP_DRIFT_SECS);

        if map.contains_key(signature) {
            return Err(AuthError::ReplayDetected);
        }

        map.insert(signature.to_string(), timestamp);
        Ok(())
    }

    /// Clear all stored signatures from cache.
    pub fn clear(&self) {
        let mut map = self.signatures.write().unwrap();
        map.clear();
    }
}

/// Global anti-replay cache shared across signaling handshake verifications.
pub static GLOBAL_ANTI_REPLAY_CACHE: LazyLock<AntiReplayCache> =
    LazyLock::new(AntiReplayCache::new);

/// Verify HTTP `Authorization` header value per WPIP-02 Section 2.2 with a specific Anti-Replay cache.
pub fn verify_authorization_header_with_cache(
    header_val: &str,
    sdp_offer: &str,
    cache: &AntiReplayCache,
) -> Result<UserAddress, AuthError> {
    let val = header_val
        .strip_prefix("WP-Ed25519 ")
        .ok_or_else(|| AuthError::InvalidScheme(header_val.to_string()))?;
    let parts: Vec<&str> = val.split(':').collect();
    if parts.len() != 3 {
        return Err(AuthError::InvalidHeaderFormat);
    }
    let pubkey_hex = parts[0];
    let timestamp: u64 = parts[1].parse().map_err(|_| AuthError::InvalidTimestamp)?;
    let sig_hex = parts[2];

    let now = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();
    let diff = now.abs_diff(timestamp);
    if diff > MAX_TIMESTAMP_DRIFT_SECS {
        return Err(AuthError::TimestampDrift {
            diff,
            max: MAX_TIMESTAMP_DRIFT_SECS,
        });
    }

    let addr = UserAddress::new(pubkey_hex);
    let payload = format!("{}:{}", timestamp, sdp_offer);
    if !UserKeypair::verify(&addr, payload.as_bytes(), sig_hex) {
        return Err(AuthError::InvalidEd25519Signature);
    }

    cache.check_and_insert(sig_hex, timestamp, now)?;

    Ok(addr)
}

/// Verify HTTP `Authorization` header value per WPIP-02 Section 2.2 using the global Anti-Replay cache.
pub fn verify_authorization_header(
    header_val: &str,
    sdp_offer: &str,
) -> Result<UserAddress, AuthError> {
    verify_authorization_header_with_cache(header_val, sdp_offer, &GLOBAL_ANTI_REPLAY_CACHE)
}

use k256::schnorr::{
    Signature as SchnorrSignature, VerifyingKey as SchnorrVerifyingKey, signature::Verifier,
};

/// Verify HTTP `Authorization` header value per WPIP-16 (secp256k1 BIP-340 Schnorr signature) with a specific Anti-Replay cache.
pub fn verify_secp256k1_authorization_header_with_cache(
    header_val: &str,
    sdp_offer: &str,
    cache: &AntiReplayCache,
) -> Result<UserAddress, AuthError> {
    let val = header_val
        .strip_prefix("WP-Secp256k1 ")
        .ok_or_else(|| AuthError::InvalidScheme(header_val.to_string()))?;
    let parts: Vec<&str> = val.split(':').collect();
    if parts.len() != 3 {
        return Err(AuthError::InvalidHeaderFormat);
    }
    let pubkey_hex = parts[0];
    let timestamp: u64 = parts[1].parse().map_err(|_| AuthError::InvalidTimestamp)?;
    let sig_hex = parts[2];

    let now = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();
    let diff = now.abs_diff(timestamp);
    if diff > MAX_TIMESTAMP_DRIFT_SECS {
        return Err(AuthError::TimestampDrift {
            diff,
            max: MAX_TIMESTAMP_DRIFT_SECS,
        });
    }

    let pubkey_bytes = hex::decode(pubkey_hex).map_err(|e| AuthError::InvalidHex(e.to_string()))?;
    let verifying_key = SchnorrVerifyingKey::from_bytes(&pubkey_bytes)
        .map_err(|_| AuthError::InvalidSecp256k1Key)?;

    let sig_bytes = hex::decode(sig_hex).map_err(|e| AuthError::InvalidHex(e.to_string()))?;
    let signature = SchnorrSignature::try_from(sig_bytes.as_slice())
        .map_err(|_| AuthError::InvalidSecp256k1Signature)?;

    let payload = format!("{}:{}", timestamp, sdp_offer);
    if verifying_key
        .verify(payload.as_bytes(), &signature)
        .is_err()
    {
        return Err(AuthError::InvalidSecp256k1Signature);
    }

    cache.check_and_insert(sig_hex, timestamp, now)?;

    Ok(UserAddress::new(pubkey_hex))
}

/// Verify HTTP `Authorization` header value per WPIP-16 (secp256k1 BIP-340 Schnorr signature) using the global Anti-Replay cache.
pub fn verify_secp256k1_authorization_header(
    header_val: &str,
    sdp_offer: &str,
) -> Result<UserAddress, AuthError> {
    verify_secp256k1_authorization_header_with_cache(
        header_val,
        sdp_offer,
        &GLOBAL_ANTI_REPLAY_CACHE,
    )
}

impl Default for UserAddress {
    fn default() -> Self {
        Self::generate_from_time()
    }
}

impl fmt::Display for UserAddress {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.id)
    }
}

impl FromStr for UserAddress {
    type Err = std::convert::Infallible;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        Ok(Self {
            id: s.trim().to_string(),
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_ed25519_keypair_sign_verify() {
        let keypair = UserKeypair::generate();
        let pubkey_addr = keypair.public_key_address();
        assert_eq!(pubkey_addr.id.len(), 64);

        let msg = b"1757275200:v=0\r\nt=0 0\r\n";
        let sig_hex = keypair.sign(msg);
        assert_eq!(sig_hex.len(), 128);

        assert!(UserKeypair::verify(&pubkey_addr, msg, &sig_hex));
        assert!(!UserKeypair::verify(&pubkey_addr, b"wrong_msg", &sig_hex));
    }

    #[test]
    fn test_authorization_header_roundtrip() {
        let keypair = UserKeypair::generate();
        let sdp = "v=0\r\no=- 123 456 IN IP4 127.0.0.1\r\n";
        let (_, header) = build_authorization_header(&keypair, sdp);
        let verified_addr = verify_authorization_header(&header, sdp).expect("Verification failed");
        assert_eq!(verified_addr, keypair.public_key_address());
    }

    #[test]
    fn test_user_address_generation_from_time() {
        let addr1 = UserAddress::generate_from_time();
        let addr2 = UserAddress::generate_from_time();

        assert_eq!(addr1.id.len(), 64);
        assert_eq!(addr2.id.len(), 64);
        assert_ne!(addr1, addr2);
    }

    #[test]
    fn test_user_address_bytes_roundtrip() {
        let addr = UserAddress::generate_from_time();
        let bytes = addr.to_bytes();
        let reconstructed = UserAddress::from_bytes(bytes);

        assert_eq!(addr, reconstructed);
    }

    #[test]
    fn test_user_address_short_id() {
        let addr = UserAddress::new("a1b2c3d4e5f607080900");
        assert_eq!(addr.short_id(), "a1b2c3d4e5f6");
    }

    #[test]
    fn test_user_address_serde() {
        let addr = UserAddress::generate_from_time();
        let json_str = serde_json::to_string(&addr).expect("Failed to serialize");
        let deserialized: UserAddress =
            serde_json::from_str(&json_str).expect("Failed to deserialize");

        assert_eq!(addr, deserialized);
    }

    #[test]
    fn test_user_address_short_id_short_length() {
        let addr = UserAddress::new("short");
        assert_eq!(addr.short_id(), "short");
    }

    #[test]
    fn test_short_id_to_bytes_roundtrip() {
        let short_addr = UserAddress::new("59ced0911ce1");
        let bytes = short_addr.to_bytes();
        assert_ne!(bytes, [0u8; 32]);
        assert_eq!(&bytes[..6], &[0x59, 0xce, 0xd0, 0x91, 0x1c, 0xe1]);
        let re_addr = UserAddress::from_bytes(bytes);
        assert!(re_addr.id.starts_with("59ced0911ce1"));
    }

    #[test]
    fn test_user_address_from_str_and_display() {
        let addr_str = "1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef";
        let parsed: UserAddress = addr_str.parse().unwrap();
        assert_eq!(parsed.to_string(), addr_str);
        assert_eq!(parsed.id, addr_str);
    }

    #[test]
    fn test_verify_secp256k1_authorization_header() {
        use k256::schnorr::SigningKey;
        use k256::schnorr::signature::Signer;
        use rand::thread_rng;

        let signing_key = SigningKey::random(&mut thread_rng());
        let verifying_key = signing_key.verifying_key();
        let pubkey_bytes = verifying_key.to_bytes();
        let pubkey_hex = hex::encode(pubkey_bytes);

        let sdp = "v=0\r\no=- 123 456 IN IP4 127.0.0.1\r\n";
        let timestamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_secs();
        let payload = format!("{}:{}", timestamp, sdp);

        let signature: SchnorrSignature = signing_key.sign(payload.as_bytes());
        let sig_hex = hex::encode(signature.to_bytes());

        let header = format!("WP-Secp256k1 {}:{}:{}", pubkey_hex, timestamp, sig_hex);

        let verified_addr = verify_secp256k1_authorization_header(&header, sdp)
            .expect("Schnorr verification should pass");
        assert_eq!(verified_addr.id, pubkey_hex);
    }

    #[test]
    fn test_nostr_keypair_and_bech32() {
        let hex_secret = "3bf0e6984b71239c4a86161427a206a1ed93ee14e04ed96f2a893339f4ad1600";
        let keypair = UserKeypair::from_nostr_key(hex_secret).expect("Failed to parse hex secret");
        assert!(keypair.is_secp256k1());

        let sdp = "v=0\r\no=- 123 456 IN IP4 127.0.0.1\r\n";
        let (_, header) = build_authorization_header(&keypair, sdp);
        assert!(header.starts_with("WP-Secp256k1 "));

        let verified_addr = verify_secp256k1_authorization_header(&header, sdp)
            .expect("Verification of generated WP-Secp256k1 header failed");
        assert_eq!(verified_addr, keypair.public_key_address());

        // Test Bech32 nsec encoding and decoding roundtrip
        let secret_bytes = hex::decode(hex_secret).unwrap();
        let nsec_encoded = encode_bech32("nsec", &secret_bytes).expect("Failed to encode nsec");
        assert!(nsec_encoded.starts_with("nsec1"));

        let nostr_kp = UserKeypair::from_nostr_key(&nsec_encoded).expect("Failed to parse nsec");
        assert!(nostr_kp.is_secp256k1());
        assert_eq!(nostr_kp.public_key_address(), keypair.public_key_address());
    }

    #[test]
    fn test_authorization_header_expired_timestamps() {
        let keypair = UserKeypair::generate();
        let sdp = "v=0\r\no=- 123 456 IN IP4 127.0.0.1\r\n";
        let now = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_secs();

        let cache = AntiReplayCache::new();

        // Expired in past (+301s drift)
        let past_ts = now.saturating_sub(301);
        let payload_past = format!("{}:{}", past_ts, sdp);
        let sig_past = keypair.sign(payload_past.as_bytes());
        let header_past = format!(
            "WP-Ed25519 {}:{}:{}",
            keypair.public_key_address().id,
            past_ts,
            sig_past
        );
        let err_past =
            verify_authorization_header_with_cache(&header_past, sdp, &cache).unwrap_err();
        assert!(matches!(err_past, AuthError::TimestampDrift { .. }));

        // Expired in future (-301s drift)
        let future_ts = now + 301;
        let payload_future = format!("{}:{}", future_ts, sdp);
        let sig_future = keypair.sign(payload_future.as_bytes());
        let header_future = format!(
            "WP-Ed25519 {}:{}:{}",
            keypair.public_key_address().id,
            future_ts,
            sig_future
        );
        let err_future =
            verify_authorization_header_with_cache(&header_future, sdp, &cache).unwrap_err();
        assert!(matches!(err_future, AuthError::TimestampDrift { .. }));

        // Valid boundary (-300s drift)
        let valid_past_ts = now.saturating_sub(300);
        let payload_valid = format!("{}:{}", valid_past_ts, sdp);
        let sig_valid = keypair.sign(payload_valid.as_bytes());
        let header_valid = format!(
            "WP-Ed25519 {}:{}:{}",
            keypair.public_key_address().id,
            valid_past_ts,
            sig_valid
        );
        assert!(verify_authorization_header_with_cache(&header_valid, sdp, &cache).is_ok());
    }

    #[test]
    fn test_authorization_header_tampered_sdp() {
        let keypair = UserKeypair::generate();
        let original_sdp = "v=0\r\no=- 123 456 IN IP4 127.0.0.1\r\n";
        let tampered_sdp = "v=0\r\no=- 999 999 IN IP4 10.0.0.1\r\n";

        let (_, header) = build_authorization_header(&keypair, original_sdp);
        let cache = AntiReplayCache::new();

        let err =
            verify_authorization_header_with_cache(&header, tampered_sdp, &cache).unwrap_err();
        assert_eq!(err, AuthError::InvalidEd25519Signature);
    }

    #[test]
    fn test_authorization_header_anti_replay() {
        let keypair = UserKeypair::generate();
        let sdp = "v=0\r\no=- 123 456 IN IP4 127.0.0.1\r\n";
        let (_, header) = build_authorization_header(&keypair, sdp);
        let cache = AntiReplayCache::new();

        // First attempt: OK
        assert!(verify_authorization_header_with_cache(&header, sdp, &cache).is_ok());

        // Replay attempt: Rejected
        let err = verify_authorization_header_with_cache(&header, sdp, &cache).unwrap_err();
        assert_eq!(err, AuthError::ReplayDetected);
    }
}
