//! Address / User ID module for identifying wclient users.
//!
//! This module provides the `UserAddress` struct representing a temporary user ID
//! generated by `wdaemon` using a SHA-256 hash of the UNIX timestamp.

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::fmt;
use std::str::FromStr;
use std::sync::atomic::{AtomicU64, Ordering};
use std::time::{SystemTime, UNIX_EPOCH};

/// Global counter for tie-breaking SHA-256 generation in the same nanosecond.
static TIME_COUNTER: AtomicU64 = AtomicU64::new(0);

/// Temporary user address / ID generated from UNIX timestamp SHA-256 hash.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct UserAddress {
    /// SHA-256 hash string (hexadecimal representation).
    pub id: String,
}

impl UserAddress {
    /// Create a `UserAddress` from a hex ID string.
    pub fn new(id: impl Into<String>) -> Self {
        Self { id: id.into() }
    }

    /// Generate a temporary `UserAddress` using SHA-256 hash derived from current UNIX timestamp.
    pub fn generate_from_time() -> Self {
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_nanos();
        let count = TIME_COUNTER.fetch_add(1, Ordering::Relaxed);

        let mut hasher = Sha256::new();
        hasher.update(format!("{}-{}", nanos, count).as_bytes());
        let result = hasher.finalize();
        let hex_id = format!("{:x}", result);

        Self { id: hex_id }
    }

    /// Convert 32-byte SHA-256 raw bytes to `UserAddress`.
    pub fn from_bytes(bytes: [u8; 32]) -> Self {
        let hex_id: String = bytes.iter().map(|b| format!("{:02x}", b)).collect();
        Self { id: hex_id }
    }

    /// Convert `UserAddress` to 32-byte raw array representation.
    pub fn to_bytes(&self) -> [u8; 32] {
        let mut bytes = [0u8; 32];
        let hex_bytes = self.id.as_bytes();
        for (i, byte) in bytes.iter_mut().enumerate() {
            if i * 2 + 1 < hex_bytes.len()
                && let Ok(val) = u8::from_str_radix(&self.id[i * 2..i * 2 + 2], 16)
            {
                *byte = val;
            }
        }
        bytes
    }

    /// Return a short 12-character preview string of the SHA-256 ID.
    pub fn short_id(&self) -> &str {
        if self.id.len() >= 12 {
            &self.id[..12]
        } else {
            &self.id
        }
    }
}

impl Default for UserAddress {
    fn default() -> Self {
        Self::generate_from_time()
    }
}

impl fmt::Display for UserAddress {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.id)
    }
}

impl FromStr for UserAddress {
    type Err = std::convert::Infallible;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        Ok(Self {
            id: s.trim().to_string(),
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_user_address_generation_from_time() {
        let addr1 = UserAddress::generate_from_time();
        let addr2 = UserAddress::generate_from_time();

        assert_eq!(addr1.id.len(), 64);
        assert_eq!(addr2.id.len(), 64);
        assert_ne!(addr1, addr2);
    }

    #[test]
    fn test_user_address_bytes_roundtrip() {
        let addr = UserAddress::generate_from_time();
        let bytes = addr.to_bytes();
        let reconstructed = UserAddress::from_bytes(bytes);

        assert_eq!(addr, reconstructed);
    }

    #[test]
    fn test_user_address_short_id() {
        let addr = UserAddress::new("a1b2c3d4e5f607080900");
        assert_eq!(addr.short_id(), "a1b2c3d4e5f6");
    }

    #[test]
    fn test_user_address_serde() {
        let addr = UserAddress::generate_from_time();
        let json_str = serde_json::to_string(&addr).expect("Failed to serialize");
        let deserialized: UserAddress =
            serde_json::from_str(&json_str).expect("Failed to deserialize");

        assert_eq!(addr, deserialized);
    }
}
