[package]
name = "wclient"
version = "0.1.0"
description = "WebTransport client for real-time audio transmission"
edition = "2024"

[dependencies]
anyhow.workspace = true
clap.workspace = true
confy.workspace = true
cpal.workspace = true
directories.workspace = true
rustls.workspace = true
serde.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
wtransport.workspace = true

[dev-dependencies]
toml = "0.8"
