/*
 * Auto-generated C API header for web-phone wpapi crate.
 * Generated by cbindgen. Do not edit manually.
 */

#ifndef WPAPI_H
#define WPAPI_H

/* Warning, this file is autogenerated by cbindgen. Don't edit this file manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Maximum allowable time drift (±300 seconds) for Authorization header timestamps (WPIP-02 / WPIP-16).
 */
#define MAX_TIMESTAMP_DRIFT_SECS 300

/**
 * Maximum allowed entries in the anti-replay signature cache.
 */
#define MAX_ANTI_REPLAY_CACHE_SIZE 10000

/**
 * Default Opus Codec ID as defined in WPIP-04.
 */
#define CODEC_OPUS 1

/**
 * PCM 32-bit float LE Codec ID.
 */
#define CODEC_PCM_F32LE 0

/**
 * PCM 16-bit signed integer LE Codec ID.
 */
#define CODEC_PCM_S16LE 2

/**
 * Maximum allowable total packet size (1 MB / 1,048,576 bytes) per WPIP-04.
 */
#define MAX_PACKET_SIZE 1048576

/**
 * Maximum allowable audio payload size (16 KiB).
 */
#define MAX_AUDIO_PAYLOAD_SIZE 16384

/**
 * Maximum allowable active speaker addresses per notice.
 */
#define MAX_SPEAKER_ADDRESSES 64

/**
 * Header byte offset for message type tag.
 */
#define OFFSET_MSG_TYPE 0

/**
 * Field size in bytes for `UserAddress` raw byte payload (32 bytes).
 */
#define LEN_USER_ADDR 32

/**
 * Field size in bytes for `client_id` (8 bytes LE u64).
 */
#define LEN_CLIENT_ID 8

/**
 * Field size in bytes for `participant_count` (4 bytes LE u32).
 */
#define LEN_PARTICIPANT_COUNT 4

/**
 * Field size in bytes for timestamp (8 bytes LE u64).
 */
#define LEN_TIMESTAMP 8

/**
 * Minimum packet length requirements for decoding validation.
 */
#define MIN_LEN_CLIENT_ASSIGNMENT (1 + LEN_CLIENT_ID)

/**
 * Full length required for ClientAssignment packet (41 bytes).
 */
#define FULL_LEN_CLIENT_ASSIGNMENT ((1 + LEN_CLIENT_ID) + LEN_USER_ADDR)

/**
 * Minimum length required for ClientTargetedAudio packet (34 bytes).
 */
#define MIN_LEN_CLIENT_TARGETED_AUDIO ((1 + LEN_USER_ADDR) + 1)

/**
 * Minimum length required for ServerTargetedAudio packet (74 bytes).
 */
#define MIN_LEN_SERVER_TARGETED_AUDIO ((((1 + LEN_USER_ADDR) + LEN_CLIENT_ID) + LEN_USER_ADDR) + 1)

/**
 * Minimum length required for PeerTargetedAudio packet (83 bytes).
 */
#define MIN_LEN_PEER_TARGETED_AUDIO ((((((1 + LEN_CLIENT_ID) + LEN_CLIENT_ID) + LEN_USER_ADDR) + LEN_USER_ADDR) + 1) + 1)

/**
 * Minimum length required for CallRequest packet (41 bytes).
 */
#define MIN_LEN_CALL_REQUEST ((1 + LEN_CLIENT_ID) + LEN_USER_ADDR)

/**
 * Minimum length required for address-only response packets (33 bytes).
 */
#define MIN_LEN_ADDRESS_ONLY_PACKET (1 + LEN_USER_ADDR)

/**
 * Minimum length required for RoomStateNotification packet (37 bytes).
 */
#define MIN_LEN_ROOM_STATE_NOTIFICATION ((1 + LEN_USER_ADDR) + LEN_PARTICIPANT_COUNT)

/**
 * Minimum length required for Ping/Pong packets (9 bytes).
 */
#define MIN_LEN_PING_PONG (1 + LEN_TIMESTAMP)

/**
 * Minimum length required for VideoFrameData packet (34 bytes).
 */
#define MIN_LEN_VIDEO_FRAME_DATA ((1 + LEN_USER_ADDR) + 1)

/**
 * Minimum length required for RoomGroupAudioE2EE packet (35 bytes).
 */
#define MIN_LEN_ROOM_GROUP_AUDIO_E2EE (((1 + LEN_USER_ADDR) + 1) + 1)

/**
 * Maximum allowed TTL for ephemeral TURN credentials (24 hours).
 */
#define MAX_TURN_TTL_SECS 86400

/**
 * Log levels for WPAPI log callback.
 * 0 = DEBUG, 1 = INFO, 2 = WARN, 3 = ERROR
 */
typedef enum WPAPILogLevel {
  /**
   * Debug severity level (0)
   */
  Debug = 0,
  /**
   * Info severity level (1)
   */
  Info = 1,
  /**
   * Warn severity level (2)
   */
  Warn = 2,
  /**
   * Error severity level (3)
   */
  Error = 3,
} WPAPILogLevel;

/**
 * Event types emitted by wpapi session event callback.
 * 0 = EventAccepted, 1 = EventRejected, 2 = EventError, 3 = EventHangup, 4 = EventIncomingCall
 */
typedef enum WPAPIEventType {
  /**
   * Call request was accepted (0)
   */
  EventAccepted = 0,
  /**
   * Call request was rejected (1)
   */
  EventRejected = 1,
  /**
   * Call connection error occurred (2)
   */
  EventError = 2,
  /**
   * Call was hung up / ended (3)
   */
  EventHangup = 3,
  /**
   * Incoming call request received (4)
   */
  EventIncomingCall = 4,
} WPAPIEventType;

/**
 * Opaque handle representing an active audio call session.
 */
typedef struct WPAPICallHandle WPAPICallHandle;

/**
 * Opaque configuration handle for wpclient.
 */
typedef struct WPAPIConfig WPAPIConfig;

/**
 * Function pointer type for log callbacks.
 */
typedef void (*WPAPILogCallback)(enum WPAPILogLevel level, const char *message, void *user_data);

/**
 * Function pointer type for session event callbacks.
 *
 * # Threading & Pointer Lifetime Rules
 * - **Threading**: The callback is invoked from a Rust Tokio background worker thread.
 *   Binding authors for runtimes like Python (GIL), Node.js (V8 loop), or Erlang (NIF) MUST
 *   bridge to the target language thread/event loop accordingly.
 * - **Pointer Lifetime**: `peer_address` and `detail_message` are temporary null-terminated C strings
 *   valid ONLY for the duration of the callback execution. Callers MUST copy these strings
 *   immediately if they need to be stored.
 */
typedef void (*WPAPIEventCallback)(enum WPAPIEventType event_type,
                                   const char *peer_address,
                                   const char *detail_message,
                                   void *user_data);

/**
 * Retrieve the last thread-local C FFI error message.
 *
 * # Safety
 * The returned pointer is managed thread-locally and remains valid until the next FFI call on the same thread.
 */
const char *wpapi_get_last_error(void);

/**
 * Copy the last thread-local C FFI error message into a caller-supplied buffer.
 * Returns 0 on success, or -1 if no error is present or buffer is invalid.
 *
 * # Safety
 * `buf` must be a valid pointer to a writeable memory buffer of at least `buf_len` bytes.
 */
int wpapi_get_last_error_copy(char *buf, uintptr_t buf_len);

/**
 * Free a C string allocated by `wpapi_list_audio_devices` or other FFI calls.
 * # Safety
 * `ptr` must be a pointer allocated by Rust FFI, or NULL.
 */
void wpapi_string_free(char *ptr);

/**
 * Query available audio input and output devices as a JSON object string.
 * Caller must free `*out_json` using `wpapi_string_free`.
 * # Safety
 * `out_json` must be a valid non-null pointer.
 */
int wpapi_list_audio_devices(char **out_json);

/**
 * Query registered user addresses from wpdaemon server as a JSON string array.
 * Caller must free `*out_json` using `wpapi_string_free`.
 * # Safety
 * `config` and `out_json` must be valid non-null pointers.
 */
int wpapi_list_addresses(const struct WPAPIConfig *config, char **out_json);

/**
 * Retrieve the last thread-local error message string.
 *
 * # Safety
 * The returned pointer is thread-local and valid until the next FFI error call on the current thread.
 */
const char *wpapi_last_error_message(void);

/**
 * Register a custom C log callback function.
 * # Safety
 * `user_data` must remain valid for the duration of registration.
 */
void wpapi_set_log_callback(WPAPILogCallback callback, void *user_data);

/**
 * Initialize tracing subscriber for logging output.
 */
int wpapi_init(void);

/**
 * Create a new client configuration handle with default settings.
 */
struct WPAPIConfig *wpapi_config_new(void);

/**
 * Free a configuration handle created with `wpapi_config_new`.
 * # Safety
 * `config` must be a valid pointer created by `wpapi_config_new`, or NULL.
 */
void wpapi_config_free(struct WPAPIConfig *config);

/**
 * Set server IP address (IPv4 or IPv6 string) and port.
 * # Safety
 * `config` and `server_ip` must be valid non-null pointers.
 */
int wpapi_config_set_server(struct WPAPIConfig *config,
                            const char *server_ip,
                            uint16_t server_port);

/**
 * Set server URL string (e.g. "<http://127.0.0.1:15000>", "<https://daemon.example.com:8443>").
 * # Safety
 * `config` and `server_url` must be valid non-null pointers.
 */
int wpapi_config_set_server_url(struct WPAPIConfig *config, const char *server_url);

/**
 * Set STUN server URL.
 * # Safety
 * `config` and `stun_server` must be valid non-null pointers.
 */
int wpapi_config_set_stun_server(struct WPAPIConfig *config, const char *stun_server);

/**
 * Set auto-accept flag for incoming call requests without CLI prompts.
 * # Safety
 * `config` must be a valid non-null pointer.
 */
int wpapi_config_set_auto_accept(struct WPAPIConfig *config, bool auto_accept);

/**
 * Set allow-echoback flag.
 * # Safety
 * `config` must be a valid non-null pointer.
 */
int wpapi_config_set_allow_echoback(struct WPAPIConfig *config, bool allow_echoback);

/**
 * Set input/output audio device substring overrides.
 * # Safety
 * `config` must be a valid non-null pointer.
 */
int wpapi_config_set_audio_devices(struct WPAPIConfig *config,
                                   const char *input_device,
                                   const char *output_device);

/**
 * Register a custom C session event callback function on the configuration handle.
 * # Safety
 * `config` must be a valid non-null pointer. `user_data` must remain valid during session execution.
 */
int wpapi_config_set_event_callback(struct WPAPIConfig *config,
                                    WPAPIEventCallback callback,
                                    void *user_data);

/**
 * Start an audio call session in a background worker thread.
 * # Safety
 * `config` must be a valid non-null pointer.
 */
struct WPAPICallHandle *wpapi_call_start(const struct WPAPIConfig *config,
                                         const char *target_address);

/**
 * Start an audio group room call (WPIP-08) in a background worker thread.
 * # Safety
 * `config` must be a valid non-null pointer.
 */
struct WPAPICallHandle *wpapi_room_call_start(const struct WPAPIConfig *config,
                                              const char *room_address);

/**
 * Send an asynchronous stop signal to an active call session without blocking.
 * Call `wpapi_call_free` later to free the handle memory after completion.
 * # Safety
 * `handle` must be a valid non-null pointer to `WPAPICallHandle`.
 */
int wpapi_call_request_stop(struct WPAPICallHandle *handle);

/**
 * Free a call session handle, blocking until worker thread cleanup completes if needed.
 * # Safety
 * `handle` must be a valid pointer created by `wpapi_call_start` or `wpapi_room_call_start`, or NULL.
 */
int wpapi_call_free(struct WPAPICallHandle *handle);

/**
 * Stop and terminate an active call session, freeing its handle.
 * # Safety
 * `handle` must be a valid pointer created by `wpapi_call_start` or `wpapi_room_call_start`, or NULL.
 */
int wpapi_call_stop(struct WPAPICallHandle *handle);

/**
 * Accept a pending incoming call request for the call session.
 * # Safety
 * `handle` must be a valid non-null pointer to `WPAPICallHandle`.
 */
int wpapi_call_accept(struct WPAPICallHandle *handle);

/**
 * Reject a pending incoming call request for the call session.
 * # Safety
 * `handle` must be a valid non-null pointer to `WPAPICallHandle`.
 */
int wpapi_call_reject(struct WPAPICallHandle *handle);

/**
 * Set microphone mute state for an active call session.
 * # Safety
 * `handle` must be a valid non-null pointer to `WPAPICallHandle`.
 */
int wpapi_call_set_muted(struct WPAPICallHandle *handle, bool muted);

/**
 * Check if microphone is currently muted for an active call session.
 * # Safety
 * `handle` must be a valid non-null pointer to `WPAPICallHandle`.
 */
bool wpapi_call_is_muted(const struct WPAPICallHandle *handle);

/**
 * Get current input audio energy level (0.0..=1.0) for an active call session.
 * # Safety
 * `handle` must be a valid non-null pointer to `WPAPICallHandle`.
 */
float wpapi_call_get_input_level(const struct WPAPICallHandle *handle);

/**
 * Get current output audio energy level (0.0..=1.0) for an active call session.
 * # Safety
 * `handle` must be a valid non-null pointer to `WPAPICallHandle`.
 */
float wpapi_call_get_output_level(const struct WPAPICallHandle *handle);

#endif  /* WPAPI_H */
