/*
 * Auto-generated C API header for web-phone wpapi crate.
 * Generated by cbindgen. Do not edit manually.
 */

#ifndef WPAPI_H
#define WPAPI_H

/* Warning, this file is autogenerated by cbindgen. Don't edit this file manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Maximum allowable time drift (±300 seconds) for Authorization header timestamps (WPIP-02 / WPIP-16).
 */
#define MAX_TIMESTAMP_DRIFT_SECS 300

/**
 * Maximum allowed entries in the anti-replay signature cache.
 */
#define MAX_ANTI_REPLAY_CACHE_SIZE 10000

/**
 * Default Opus Codec ID as defined in WPIP-04.
 */
#define CODEC_OPUS 1

/**
 * PCM 32-bit float LE Codec ID.
 */
#define CODEC_PCM_F32LE 0

/**
 * PCM 16-bit signed integer LE Codec ID.
 */
#define CODEC_PCM_S16LE 2

/**
 * Maximum allowable total packet size (1 MB / 1,048,576 bytes) per WPIP-04.
 */
#define MAX_PACKET_SIZE 1048576

/**
 * Maximum allowable audio payload size (16 KiB).
 */
#define MAX_AUDIO_PAYLOAD_SIZE 16384

/**
 * Maximum allowable active speaker addresses per notice.
 */
#define MAX_SPEAKER_ADDRESSES 64

/**
 * Header byte offset for message type tag.
 */
#define OFFSET_MSG_TYPE 0

/**
 * Field size in bytes for `UserAddress` raw byte payload (32 bytes).
 */
#define LEN_USER_ADDR 32

/**
 * Field size in bytes for `client_id` (8 bytes LE u64).
 */
#define LEN_CLIENT_ID 8

/**
 * Field size in bytes for `participant_count` (4 bytes LE u32).
 */
#define LEN_PARTICIPANT_COUNT 4

/**
 * Field size in bytes for timestamp (8 bytes LE u64).
 */
#define LEN_TIMESTAMP 8

/**
 * Minimum packet length requirements for decoding validation.
 */
#define MIN_LEN_CLIENT_ASSIGNMENT (1 + LEN_CLIENT_ID)

#define FULL_LEN_CLIENT_ASSIGNMENT ((1 + LEN_CLIENT_ID) + LEN_USER_ADDR)

#define MIN_LEN_CLIENT_TARGETED_AUDIO ((1 + LEN_USER_ADDR) + 1)

#define MIN_LEN_SERVER_TARGETED_AUDIO ((((1 + LEN_USER_ADDR) + LEN_CLIENT_ID) + LEN_USER_ADDR) + 1)

#define MIN_LEN_PEER_TARGETED_AUDIO ((((((1 + LEN_CLIENT_ID) + LEN_CLIENT_ID) + LEN_USER_ADDR) + LEN_USER_ADDR) + 1) + 1)

#define MIN_LEN_CALL_REQUEST ((1 + LEN_CLIENT_ID) + LEN_USER_ADDR)

#define MIN_LEN_ADDRESS_ONLY_PACKET (1 + LEN_USER_ADDR)

#define MIN_LEN_ROOM_STATE_NOTIFICATION ((1 + LEN_USER_ADDR) + LEN_PARTICIPANT_COUNT)

#define MIN_LEN_PING_PONG (1 + LEN_TIMESTAMP)

#define MIN_LEN_VIDEO_FRAME_DATA ((1 + LEN_USER_ADDR) + 1)

/**
 * Maximum allowed TTL for ephemeral TURN credentials (24 hours).
 */
#define MAX_TURN_TTL_SECS 86400

/**
 * Log levels for WPAPI log callback.
 * 0 = DEBUG, 1 = INFO, 2 = WARN, 3 = ERROR
 */
typedef enum WPAPILogLevel {
  Debug = 0,
  Info = 1,
  Warn = 2,
  Error = 3,
} WPAPILogLevel;

/**
 * Opaque handle representing an active audio call session.
 */
typedef struct WPAPICallHandle WPAPICallHandle;

/**
 * Opaque configuration handle for wpclient.
 */
typedef struct WPAPIConfig WPAPIConfig;

/**
 * Function pointer type for log callbacks.
 */
typedef void (*WPAPILogCallback)(enum WPAPILogLevel level, const char *message, void *user_data);

/**
 * Retrieve the last thread-local C FFI error message.
 *
 * # Safety
 * The returned pointer is managed thread-locally and remains valid until the next FFI call on the same thread.
 */
const char *wpapi_get_last_error(void);

/**
 * Free a C string allocated by `wpapi_list_audio_devices` or other FFI calls.
 * # Safety
 * `ptr` must be a pointer allocated by Rust FFI, or NULL.
 */
void wpapi_string_free(char *ptr);

/**
 * Query available audio input and output devices as a JSON object string.
 * Caller must free `*out_json` using `wpapi_string_free`.
 * # Safety
 * `out_json` must be a valid non-null pointer.
 */
int wpapi_list_audio_devices(char **out_json);

/**
 * Query registered user addresses from wpdaemon server as a JSON string array.
 * Caller must free `*out_json` using `wpapi_string_free`.
 * # Safety
 * `config` and `out_json` must be valid non-null pointers.
 */
int wpapi_list_addresses(const struct WPAPIConfig *config, char **out_json);

/**
 * Retrieve the last thread-local error message string.
 *
 * # Safety
 * The returned pointer is thread-local and valid until the next FFI error call on the current thread.
 */
const char *wpapi_last_error_message(void);

/**
 * Register a custom C log callback function.
 * # Safety
 * `user_data` must remain valid for the duration of registration.
 */
void wpapi_set_log_callback(WPAPILogCallback callback, void *user_data);

/**
 * Initialize tracing subscriber for logging output.
 */
int wpapi_init(void);

/**
 * Create a new client configuration handle with default settings.
 */
struct WPAPIConfig *wpapi_config_new(void);

/**
 * Free a configuration handle created with `wpapi_config_new`.
 * # Safety
 * `config` must be a valid pointer created by `wpapi_config_new`, or NULL.
 */
void wpapi_config_free(struct WPAPIConfig *config);

/**
 * Set server IP address (IPv4 or IPv6 string) and port.
 * # Safety
 * `config` and `server_ip` must be valid non-null pointers.
 */
int wpapi_config_set_server(struct WPAPIConfig *config,
                            const char *server_ip,
                            uint16_t server_port);

/**
 * Set STUN server URL.
 * # Safety
 * `config` and `stun_server` must be valid non-null pointers.
 */
int wpapi_config_set_stun_server(struct WPAPIConfig *config, const char *stun_server);

/**
 * Set auto-accept flag for incoming call requests without CLI prompts.
 * # Safety
 * `config` must be a valid non-null pointer.
 */
int wpapi_config_set_auto_accept(struct WPAPIConfig *config, bool auto_accept);

/**
 * Set allow-echoback flag.
 * # Safety
 * `config` must be a valid non-null pointer.
 */
int wpapi_config_set_allow_echoback(struct WPAPIConfig *config, bool allow_echoback);

/**
 * Set input/output audio device substring overrides.
 * # Safety
 * `config` must be a valid non-null pointer.
 */
int wpapi_config_set_audio_devices(struct WPAPIConfig *config,
                                   const char *input_device,
                                   const char *output_device);

/**
 * Start an audio call session in a background worker thread.
 * # Safety
 * `config` must be a valid non-null pointer.
 */
struct WPAPICallHandle *wpapi_call_start(const struct WPAPIConfig *config,
                                         const char *target_address);

/**
 * Start an audio group room call (WPIP-08) in a background worker thread.
 * # Safety
 * `config` must be a valid non-null pointer.
 */
struct WPAPICallHandle *wpapi_room_call_start(const struct WPAPIConfig *config,
                                              const char *room_address);

/**
 * Stop and terminate an active call session, freeing its handle.
 * # Safety
 * `handle` must be a valid pointer.
 */
int wpapi_call_stop(struct WPAPICallHandle *handle);

#endif  /* WPAPI_H */
